In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pt
import seaborn as sns


In [2]:
df = pd.read_excel("UGP battery data.xlsx")

In [3]:
df.info

<bound method DataFrame.info of          Cathode  Li Cathode     Co  O    Mn    Ni  Fe  P  Al  Ti  ...  \
0         LiCoO2           1  1.000  2  0.00  0.00   0  0   0   0  ...   
1         LiCoO2           1  1.000  2  0.00  0.00   0  0   0   0  ...   
2         LiCoO2           1  1.000  2  0.00  0.00   0  0   0   0  ...   
3         LiCoO2           1  1.000  2  0.00  0.00   0  0   0   0  ...   
4         LiCoO2           1  1.000  2  0.00  0.00   0  0   0   0  ...   
..           ...         ...    ... ..   ...   ...  .. ..  ..  ..  ...   
379  Li Rich NMC           1  0.008  2  0.56  0.16   0  0   0   0  ...   
380  Li Rich NMC           1  0.008  2  0.56  0.16   0  0   0   0  ...   
381  Li Rich NMC           1  0.008  2  0.56  0.16   0  0   0   0  ...   
382  Li Rich NMC           1  0.008  2  0.56  0.16   0  0   0   0  ...   
383  Li Rich NMC           1  0.008  2  0.56  0.16   0  0   0   0  ...   

     Column36  Column37  Column38  Column39  Column40  Column41  Column42  \
0 

In [4]:
df.describe

<bound method NDFrame.describe of          Cathode  Li Cathode     Co  O    Mn    Ni  Fe  P  Al  Ti  ...  \
0         LiCoO2           1  1.000  2  0.00  0.00   0  0   0   0  ...   
1         LiCoO2           1  1.000  2  0.00  0.00   0  0   0   0  ...   
2         LiCoO2           1  1.000  2  0.00  0.00   0  0   0   0  ...   
3         LiCoO2           1  1.000  2  0.00  0.00   0  0   0   0  ...   
4         LiCoO2           1  1.000  2  0.00  0.00   0  0   0   0  ...   
..           ...         ...    ... ..   ...   ...  .. ..  ..  ..  ...   
379  Li Rich NMC           1  0.008  2  0.56  0.16   0  0   0   0  ...   
380  Li Rich NMC           1  0.008  2  0.56  0.16   0  0   0   0  ...   
381  Li Rich NMC           1  0.008  2  0.56  0.16   0  0   0   0  ...   
382  Li Rich NMC           1  0.008  2  0.56  0.16   0  0   0   0  ...   
383  Li Rich NMC           1  0.008  2  0.56  0.16   0  0   0   0  ...   

     Column36  Column37  Column38  Column39  Column40  Column41  Column42  \


In [5]:
df.shape

(384, 44)

In [6]:
df.dropna(axis = 'columns', inplace  =True)

In [7]:
X = df.iloc[:,1:-1].values
y = df.iloc[:,-1].values

In [8]:
y

array([166, 180, 155, 166, 178, 195, 196, 164, 158, 164, 164, 192, 195,
       179, 153, 178, 158, 169, 157, 163, 177, 190, 196, 178, 165, 160,
       157, 190, 199, 173, 153, 158, 130, 117, 138, 122, 111, 148, 133,
       104, 101, 101, 104, 125, 127, 114, 106, 113, 108, 118, 104, 118,
       120, 132, 145, 101, 115, 111, 120, 128, 129, 100, 115, 101, 167,
       150, 160, 178, 166, 188, 188, 166, 150, 155, 157, 186, 205, 168,
       174, 155, 166, 177, 178, 177, 152, 181, 220, 162, 154, 174, 180,
       198, 180, 152, 158, 172,  98,  90, 103, 102, 102, 110, 114,  96,
       105,  97, 104, 116, 116, 109,  98, 107, 103,  93,  98, 101,  91,
       120, 110,  91,  93, 108, 104, 114, 118, 102, 106, 109, 233, 211,
       214, 216, 224, 257, 247, 203, 222, 200, 238, 240, 253, 203, 234,
       207, 206, 229, 204, 225, 214, 251, 247, 228, 215, 230, 203, 251,
       250, 203, 224, 211,  72,  70,  72,  70,  75,  80,  76,  71,  71,
        73,  70,  79,  78,  75,  72,  73,  74,  75,  70,  75,  7

In [9]:
df.shape

(384, 29)

In [10]:
X

array([[1.   , 1.   , 2.   , ..., 0.   , 0.   , 0.   ],
       [1.   , 1.   , 2.   , ..., 0.   , 0.   , 0.   ],
       [1.   , 1.   , 2.   , ..., 0.   , 0.   , 0.   ],
       ...,
       [1.   , 0.008, 2.   , ..., 1.   , 0.   , 0.   ],
       [1.   , 0.008, 2.   , ..., 0.   , 1.   , 0.   ],
       [1.   , 0.008, 2.   , ..., 0.   , 0.   , 1.   ]])

In [11]:
#Splitting the data to train, test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
X_train

array([[1., 0., 4., ..., 0., 0., 0.],
       [1., 1., 2., ..., 0., 0., 0.],
       [2., 0., 3., ..., 0., 0., 0.],
       ...,
       [1., 0., 4., ..., 0., 0., 0.],
       [1., 0., 4., ..., 0., 0., 1.],
       [2., 0., 3., ..., 0., 0., 0.]])

In [12]:
# X_train = X_train[:,:12] + X_train[:,13:]

In [13]:
y_train.shape`

SyntaxError: invalid syntax (<ipython-input-13-079bf24ba57e>, line 1)

In [ ]:
#LinearRegression
from sklearn.linear_model import LinearRegression
lreg = LinearRegression()
lreg.fit(X_train,y_train)

In [ ]:
y_pred = lreg.predict(X_test)
y_pred

In [ ]:
pt.plot(y_test)
pt.plot(y_pred)

In [ ]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test,y_pred)
print(r2)

In [ ]:
pt.figure(figsize=(20,15))
p=sns.heatmap(df.corr(),annot=True,cmap="RdYlGn")

In [ ]:
# sample = np.array(X[0,:])
# c_n = list(df.columns.values)
# print(len(sample))
# print(len(c_n))

In [ ]:
# c_n = c_n[1:-1]
# print(sample)

In [ ]:
# print(len(sample))
# print(len(c_n))

In [ ]:
# np.stack((c_n, sample))
# import sys
# import numpy
# numpy.set_printoptions(threshold=sys.maxsize)

In [ ]:
# np.stack((c_n, sample))

In [ ]:
new = [1,1,2,0,0,0,0,0,0,1,0, 0, 0, 0, 0, 0, 1, 2, 0,0, 0, 0, 0, 0, 0,0,0]
len(new)
new

In [ ]:
# f_new = ["%.2f" % elem for elem in new]
p = np.array(new)
p = p.reshape(1,-1)
print(p)
print(lreg.predict(p))

In [ ]:
print(lreg.predict(p))